# Generated by Django 4.1.7 on 2023-04-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'contactUs', 'verbose_name_plural': 'contactUss'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='place',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
