# Generated by Django 4.1.7 on 2023-04-04 00:00

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', upload_to=job.models.imageUpload),
            preserve_default=False,
        ),
    ]
