# Generated by Django 4.1.7 on 2023-04-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_jobrequirements_job_jobresponsibilities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='apply/')),
                ('linkedIn', models.URLField()),
                ('cover', models.CharField(max_length=350)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='OtherBenifits',
        ),
    ]
