# Generated by Django 4.1.7 on 2023-04-05 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_applyreq_remove_job_otherbenifits'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyreq',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.job', verbose_name='applyJob'),
            preserve_default=False,
        ),
    ]
