# Generated by Django 4.1.7 on 2023-04-06 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_applyreq_age_applyreq_applied_at_applyreq_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyreq',
            name='cv',
        ),
    ]
