# Generated by Django 4.1.7 on 2023-04-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_remove_applyreq_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyreq',
            name='cv',
            field=models.FileField(default='', upload_to='apply/'),
            preserve_default=False,
        ),
    ]
